# default application settings (can be overridden according to Spring Boot docs)

core_version_list: # where to fetch list of OpenMRS core versions
  url: https://openmrs.jfrog.io/openmrs/api/storage/public/org/openmrs/api/openmrs-api/
  strategy: FETCH  # FETCH is production behavior; LOCAL uses the local resource, e.g. for testing

add_on_list: # where/how to fetch our master list of add-ons from
  url: https://raw.githubusercontent.com/openmrs/openmrs-contrib-addonindex/master/src/main/resources/add-ons-to-index.json
  strategy: FETCH  # FETCH is production behavior; LOCAL uses the local resource, e.g. for testing

bintray:
  username:  # override in your local config (you should belong to OpenMRS or Bintray will rate limit you)
  api_key:  # override in your local config

scheduler:
  fetch_core_versions_list:     # for each add-on we want to index, fetch its details
    initial_delay: 5000      # wait 5 seconds to start
    period: 14400000          # execute every 4 hours

  fetch_add_on_list:     # fetches our master list of add-ons that we should index (from github)
    initial_delay: 8000  # wait 8 seconds to start
    period: 14400000     # execute every 4 hours

  fetch_details_to_index:     # for each add-on we want to index, fetch its details
    initial_delay: 15000      # wait 15 seconds to start
    period: 14400000          # execute every 4 hours
    fetch_extra_details: true # get each addon version and inspect it for Required OpenMRS, etc

  analysis:
    count_top_downloads:
      initial_delay: 10000  # wait 10 seconds to start
      period: 1800000       # execute 30 minutes


spring.elasticsearch.jest:
  uris: http://localhost:9200